version: "3.3"
services:
  app:
    build: .

  postgres12:
    image: postgres:12
    environment:
      POSTGRES_DB: "kokoc"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "mypassword"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres12:/var/lib/postgresql/data

volumes:
  postgres12:
    driver: local
